#!/usr/bin/env python3
"""One-way synchronization from canonical Codex agents to Qoder agents.

The reusable HOI4 starter supports two agent runtimes:

* ``.codex/agents/*.toml`` is the canonical authoring source.
* ``.qoder/agents/*.md`` is generated output and must not be hand-edited.

Run ``python .tools/sync_qoder_agents.py`` after changing a Codex agent. Use
``--check`` in validation or CI to detect missing, stale, or outdated output.
The script reads but never writes ``.codex``.
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # Python 3.9/3.10 fallback
    except ModuleNotFoundError:
        sys.exit(
            "ERROR: no TOML parser available. Install tomli "
            "(python -m pip install tomli) or use Python 3.11+."
        )


MOD_ROOT = Path(__file__).resolve().parent.parent
CODEX_AGENTS = MOD_ROOT / ".codex" / "agents"
QODER_AGENTS = MOD_ROOT / ".qoder" / "agents"
NAME_PATTERN = re.compile(r"^hoi4_[a-z0-9]+(?:_[a-z0-9]+)*$")

# Keep substitutions mechanical and minimal so the TOML prompt remains the
# canonical wording. These phrases describe runtime orchestration rather than
# the agent's HOI4 responsibility.
BODY_SUBSTITUTIONS = (
    (
        r"fork_context=false",
        "a fully explicit, self-contained prompt (no inherited conversation context)",
    ),
    (r"Agent Nudger writes", "UI-assisted writes"),
    (r"Codex's official \$imagegen skill", "the runtime's official image-generation skill"),
)

# Qoder tool access is intentionally coarse. The generated prompt body remains
# the authoritative scope contract from the hoi4-subagents skill.
TOOLS_READONLY = "Read, Grep, Glob, Bash, Write"
TOOLS_PATCH = "Read, Grep, Glob, Bash, Edit, Write"
TOOLS_ASSET_WEB = TOOLS_PATCH + ", WebFetch, WebSearch"

AUTHORITY = {
    # Read-only or plan-only (Write is available for requested reports/plans).
    "hoi4_repo_explorer": TOOLS_READONLY,
    "hoi4_feature_completion_auditor": TOOLS_READONLY,
    "hoi4_ai_probability_auditor": TOOLS_READONLY,
    "hoi4_improvement_loop_planner": TOOLS_READONLY,
    # Documentation and narrow patch roles.
    "hoi4_documentation_curator": TOOLS_PATCH,
    "hoi4_scripted_system_architect": TOOLS_PATCH,
    "hoi4_decision_mission_auditor": TOOLS_PATCH,
    "hoi4_focus_tree_auditor": TOOLS_PATCH,
    "hoi4_country_package_auditor": TOOLS_PATCH,
    "hoi4_localisation_auditor": TOOLS_PATCH,
    "hoi4_event_ui_worker": TOOLS_PATCH,
    "hoi4_skill_maintainer": TOOLS_PATCH,
    "hoi4_spreadsheet_doc_worker": TOOLS_PATCH,
    # Asset production and sourced research roles.
    "hoi4_asset_source_researcher": TOOLS_ASSET_WEB,
    "hoi4_generated_feature_art": TOOLS_ASSET_WEB,
    "hoi4_icon_artist": TOOLS_ASSET_WEB,
    "hoi4_portrait_creator": TOOLS_ASSET_WEB,
    "hoi4_audio_researcher": TOOLS_ASSET_WEB,
    "hoi4_quote_remark_researcher": TOOLS_ASSET_WEB,
    "hoi4_super_event_art_researcher": TOOLS_ASSET_WEB,
    "hoi4_super_event_audio_researcher": TOOLS_ASSET_WEB,
    "hoi4_super_event_quote_researcher": TOOLS_ASSET_WEB,
    "hoi4_3d_model_pipeline": TOOLS_ASSET_WEB,
}

GENERATED_BANNER = (
    "<!-- GENERATED FILE: regenerated from .codex/agents/{src} by\n"
    "     python .tools/sync_qoder_agents.py. Do not hand-edit;\n"
    "     change the Codex TOML source and rerun the sync script. -->\n"
)

README_TEMPLATE = """<!-- GENERATED FILE: regenerated by python .tools/sync_qoder_agents.py. -->
# Qoder Subagents (Generated)

Every file in this folder is generated from the canonical Codex definitions in
`.codex/agents/` by `python .tools/sync_qoder_agents.py`. Do not hand-edit the
generated files. Edit `.codex/agents/<name>.toml`, then rerun the sync script.

## Name mapping

Qoder accepts lowercase letters and hyphens in subagent names, so canonical
snake-case Codex identifiers map to hyphen-case Qoder identifiers.

| Canonical (Codex) | Qoder | Authority |
| --- | --- | --- |
{rows}

Authority classes follow the `hoi4-subagents` skill. Frontmatter tool access is
coarse; each generated agent's prompt body is its authoritative scope contract.
"""


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift without creating or updating generated files",
    )
    return parser.parse_args()


def load_toml(path):
    with path.open("rb") as handle:
        return tomllib.load(handle)


def apply_substitutions(body):
    result = body
    for pattern, replacement in BODY_SUBSTITUTIONS:
        result = re.sub(pattern, replacement, result)
    return result.strip() + "\n"


def yaml_quote(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"{}"'.format(escaped)


def render_agent(name, description, body, src_name):
    qoder_name = name.replace("_", "-")
    lines = [
        "---",
        "name: {}".format(qoder_name),
        "description: {}".format(yaml_quote(description)),
        "tools: {}".format(AUTHORITY[name]),
        "---",
        "",
    ]
    return "\n".join(lines) + GENERATED_BANNER.format(src=src_name) + "\n" + body


def authority_label(tools):
    if tools == TOOLS_READONLY:
        return "read-only / plan-only"
    if tools == TOOLS_PATCH:
        return "patch-capable"
    return "asset / research (web)"


def collect_outputs():
    if not CODEX_AGENTS.is_dir():
        raise ValueError("canonical source folder not found: {}".format(CODEX_AGENTS))

    toml_paths = sorted(CODEX_AGENTS.glob("*.toml"))
    if not toml_paths:
        raise ValueError("no canonical agent definitions found in {}".format(CODEX_AGENTS))

    outputs = {}
    rows = []
    seen_names = set()
    for toml_path in toml_paths:
        data = load_toml(toml_path)
        name = data.get("name") or toml_path.stem
        description = data.get("description", "").strip()
        instructions = data.get("developer_instructions", "").strip()

        if name != toml_path.stem:
            raise ValueError("{} declares name {!r}; expected {!r}".format(
                toml_path, name, toml_path.stem
            ))
        if not NAME_PATTERN.fullmatch(name):
            raise ValueError("{} has an invalid reusable HOI4 agent name: {!r}".format(
                toml_path, name
            ))
        if name in seen_names:
            raise ValueError("duplicate canonical agent name: {}".format(name))
        if name not in AUTHORITY:
            raise ValueError(
                "{} has no authority mapping; classify every canonical agent explicitly".format(name)
            )
        if not description or not instructions:
            raise ValueError(
                "{} is missing description or developer_instructions".format(toml_path)
            )

        seen_names.add(name)
        qoder_name = name.replace("_", "-")
        filename = "{}.md".format(qoder_name)
        outputs[filename] = render_agent(
            name,
            description,
            apply_substitutions(instructions),
            toml_path.name,
        )
        rows.append("| `{}` | `{}` | {} |".format(
            name, qoder_name, authority_label(AUTHORITY[name])
        ))

    unused = sorted(set(AUTHORITY) - seen_names)
    if unused:
        raise ValueError("authority mappings have no canonical TOML: {}".format(", ".join(unused)))

    outputs["README.md"] = README_TEMPLATE.format(rows="\n".join(rows))
    return outputs


def find_drift(outputs):
    drift = []
    for filename, content in outputs.items():
        path = QODER_AGENTS / filename
        if not path.exists():
            drift.append((filename, "missing"))
        elif path.read_text(encoding="utf-8") != content:
            drift.append((filename, "outdated"))

    if QODER_AGENTS.is_dir():
        expected = set(outputs)
        drift.extend(
            (path.name, "stale")
            for path in sorted(QODER_AGENTS.glob("*.md"))
            if path.name not in expected
        )
    return drift


def sync(outputs):
    QODER_AGENTS.mkdir(parents=True, exist_ok=True)
    created = updated = unchanged = 0
    for filename, content in outputs.items():
        path = QODER_AGENTS / filename
        if path.exists() and path.read_text(encoding="utf-8") == content:
            unchanged += 1
            continue
        existed = path.exists()
        with path.open("w", encoding="utf-8", newline="") as handle:
            handle.write(content)
        if existed:
            updated += 1
        else:
            created += 1
    return created, updated, unchanged


def main():
    args = parse_args()
    try:
        outputs = collect_outputs()
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        sys.exit("ERROR: {}".format(error))

    drift = find_drift(outputs)
    stale = [filename for filename, state in drift if state == "stale"]
    if args.check:
        if drift:
            for filename, state in drift:
                print("{}: {}".format(state.upper(), filename))
            sys.exit("ERROR: Qoder agents are not synchronized")
        print("Qoder agents are synchronized ({} generated file(s)).".format(len(outputs)))
        return

    created, updated, unchanged = sync(outputs)
    print("Synced {} generated file(s): {} created, {} updated, {} unchanged.".format(
        len(outputs), created, updated, unchanged
    ))
    if stale:
        print("WARNING: stale Markdown file(s) were not deleted: {}".format(", ".join(stale)))


if __name__ == "__main__":
    main()
